apiVersion: apps/v1 
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: scottleedavis/cozyish-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: ELASTICSEARCH_URL
          value: http://localhost:9200
        - name: MINIO
          value: localhost:9000
        - name: MINIO_ACCESS_KEY
          value: minioaccesskey
        - name: MINIO_SECRET_KEY
          value: miniosecretkey
        - name: RABBITMQ
          value: localhost:5672
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ui
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:

