apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cache-deployment
spec:
  selector:
    matchLabels:
      app: cache
  replicas: 1
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: scottleedavis/cozyish-cache:latest
        ports:
        - containerPort: 8004
        env:
        - name: ELASTICSEARCH_URL
          value: http://localhost:9200
        - name: RABBITMQ
          value: localhost:5672
---
apiVersion: v1
kind: Service
metadata:
  name: cache-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8004
    name: "8004"
    protocol: TCP
    targetPort: 8004
  selector:
    app: cache
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:

