apiVersion: apps/v1 
kind: Deployment
metadata:
  name: classify-deployment
spec:
  selector:
    matchLabels:
      app: classify
  replicas: 1
  template:
    metadata:
      labels:
        app: classify
    spec:
      containers:
      - name: classify
        image: scottleedavis/cozyish-classify:latest
        ports:
        - containerPort: 8003
        env:
        - name: DEEPDETECT
          value: localhost:8080
        - name: ELASTICSEARCH_URL
          value: http://localhost:9200
        - name: MINIO
          value: localhost:9000
        - name: MINIO_ACCESS_KEY
          value: minioaccesskey
        - name: MINIO_SECRET_KEY
          value: miniosecretkey
        - name: NSFWAPI
          value: localhost:5000
        - name: RABBITMQ
          value: localhost:5672
---
apiVersion: v1
kind: Service
metadata:
  name: classify-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8003
    name: "8003"
    protocol: TCP
    targetPort: 8003
  selector:
    app: classify
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:

