apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cozyish-deployment
spec:
  selector:
    matchLabels:
      app: cozyish
  replicas: 1
  template:
    metadata:
      labels:
        app: cozyish
    spec:
      containers:
  
      - name: rabbit
        image: bitnami/rabbitmq:3.7
        ports:
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 25672
        - containerPort: 15672
        env:
        - name: MINIO_ACCESS_KEY
          value: minioaccesskey
        - name: MINIO_SECRET_KEY
          value: miniosecretkey
        - name: MINIO_SSE_MASTER_KEY
          value: my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574
      
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: discovery.type
          value: single-node

      - name: minio
        image: minio/minio:RELEASE.2019-10-02T21-19-38Z
        ports:
        - containerPort: 9000
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: minioaccesskey
        - name: MINIO_SECRET_KEY
          value: miniosecretkey
        - name: MINIO_SSE_MASTER_KEY
          value: my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574

      - name: deepdetect
        image: jolibrain/deepdetect_cpu:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "5000"

      - name: nsfw
        image: eugencepoi/nsfw_api:latest
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: PORT
          value: "5000"


      - name: api
        image: scottleedavis/cozyish-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: ELASTICSEARCH_URL
          value: http://localhost:9200
        - name: MINIO
          value: localhost:9000
        - name: MINIO_ACCESS_KEY
          value: minioaccesskey
        - name: MINIO_SECRET_KEY
          value: miniosecretkey
        - name: RABBITMQ
          value: localhost:5672  

      - name: cache
        image: scottleedavis/cozyish-cache:latest
        ports:
        - containerPort: 8004
        env:
        - name: ELASTICSEARCH_URL
          value: http://localhost:9200
        - name: RABBITMQ
          value: localhost:5672

      - name: classify
        image: scottleedavis/cozyish-classify:latest
        ports:
        - containerPort: 8003
        env:
        - name: DEEPDETECT
          value: localhost:8080
        - name: ELASTICSEARCH_URL
          value: http://localhost:9200
        - name: MINIO
          value: localhost:9000
        - name: MINIO_ACCESS_KEY
          value: minioaccesskey
        - name: MINIO_SECRET_KEY
          value: miniosecretkey
        - name: NSFWAPI
          value: localhost:5000
        - name: RABBITMQ
          value: localhost:5672

      - name: crawler
        image: scottleedavis/cozyish-crawler:latest
        ports:
        - containerPort: 4444
        env:
        - name: API
          value: localhost:8000

      - name: extract
        image: scottleedavis/cozyish-extract:latest
        ports:
        - containerPort: 8002
        env:
        - name: ELASTICSEARCH_URL
          value: http://localhost:9200
        - name: MINIO
          value: localhost:9000
        - name: RABBITMQ
          value: localhost:5672

      - name: store
        image: scottleedavis/cozyish-store:latest
        ports:
        - containerPort: 8001
        env:
        - name: MINIO
          value: localhost:9000
        - name: MINIO_ACCESS_KEY
          value: minioaccesskey
        - name: MINIO_SECRET_KEY
          value: miniosecretkey
        - name: RABBITMQ
          value: localhost:5672

      - name: ui
        image: scottleedavis/cozyish-ui:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
  selfLink: /api/v1/namespaces/default/services/api-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: cozyish
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: default
  selfLink: /api/v1/namespaces/default/services/ui-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cozyish
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  namespace: default
  selfLink: /api/v1/namespaces/default/services/crawler-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: cozyish
  sessionAffinity: None
  type: LoadBalancer
---