apiVersion: apps/v1 
kind: Deployment
metadata:
  name: crawler-deployment
spec:
  selector:
    matchLabels:
      app: crawler
  replicas: 1
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: scottleedavis/cozyish-crawler:latest
        ports:
        - containerPort: 4444
        env:
        - name: API
          value: localhost:8000
---
apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: crawler
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:

