apiVersion: apps/v1 
kind: Deployment
metadata:
  name: deepdetect-deployment
spec:
  selector:
    matchLabels:
      app: deepdetect
  replicas: 1
  template:
    metadata:
      labels:
        app: deepdetect
    spec:
      containers:
      - name: deepdetect
        image: jolibrain/deepdetect_cpu:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: deepdetect-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: deepdetect
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:

