apiVersion: apps/v1 
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: discovery.type
          value: single-node
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9200
    name: "9200"
    protocol: TCP
    targetPort: 9200
  - port: 9300
    name: "9300"
    protocol: TCP
    targetPort: 9300
  selector:
    app: ui
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:

