apiVersion: apps/v1 
kind: Deployment
metadata:
  name: minio-deployment
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2019-10-02T21-19-38Z
        ports:
        - containerPort: 9000
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: minioaccesskey
        - name: MINIO_SECRET_KEY
          value: miniosecretkey
        - name: MINIO_SSE_MASTER_KEY
          value: my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9000
    name: "9000"
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:

