apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nsfw-deployment
spec:
  selector:
    matchLabels:
      app: nsfw
  replicas: 1
  template:
    metadata:
      labels:
        app: nsfw
    spec:
      containers:
      - name: nsfw
        image: eugencepoi/nsfw_api:latest
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: nsfw-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: nsfw
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:

