apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rabbit-deployment
spec:
  selector:
    matchLabels:
      app: rabbit
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - name: rabbit
        image: bitnami/rabbitmq:3.7
        ports:
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 25672
        - containerPort: 15672
        env:
        - name: MINIO_ACCESS_KEY
          value: minioaccesskey
        - name: MINIO_SECRET_KEY
          value: miniosecretkey
        - name: MINIO_SSE_MASTER_KEY
          value: my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 4369
    name: "4369"
    protocol: TCP
    targetPort: 4369
  - port: 5672
    name: "5672"
    protocol: TCP
    targetPort: 5672
  - port: 25672
    name: "25672"
    protocol: TCP
    targetPort: 25672
  - port: 15672
    name: "15672"
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbit
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:

