apiVersion: apps/v1 
kind: Deployment
metadata:
  name: store-deployment
spec:
  selector:
    matchLabels:
      app: store
  replicas: 1
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: scottleedavis/cozyish-store:latest
        ports:
        - containerPort: 8001
        env:
        - name: MINIO
          value: localhost:9000
        - name: MINIO_ACCESS_KEY
          value: minioaccesskey
        - name: MINIO_SECRET_KEY
          value: miniosecretkey
        - name: RABBITMQ
          value: localhost:5672
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8001
    name: "8001"
    protocol: TCP
    targetPort: 8001
  selector:
    app: store
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:

