apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: crawler
  name: crawler
spec:
  ports:
  - name: "4444"
    port: 4444
    targetPort: 4444
  selector:
    io.kompose.service: crawler
status:
  loadBalancer: {}
