apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: crawler
  name: crawler
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: crawler
    spec:
      containers:
      - env:
        - name: API
          value: api:8000
        image: crawler
        name: crawler
        ports:
        - containerPort: 4444
        resources: {}
      restartPolicy: Always
status: {}
