apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: deepdetect
  name: deepdetect
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: deepdetect
    spec:
      containers:
      - image: jolibrain/deepdetect_cpu
        name: deepdetect
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /opt/models/
          name: deepdetect-claim0
      restartPolicy: Always
      volumes:
      - name: deepdetect-claim0
        persistentVolumeClaim:
          claimName: deepdetect-claim0
status: {}
