apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: store
  name: store
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: store
    spec:
      containers:
      - env:
        - name: MINIO
          value: minio:9000
        - name: MINIO_ACCESS_KEY
          value: minioaccesskey
        - name: MINIO_SECRET_KEY
          value: miniosecretkey
        - name: RABBITMQ
          value: rabbitmq:5672
        image: store
        name: store
        resources: {}
      restartPolicy: Always
status: {}
